/*
 * File: app/store/AppInfoStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.AppInfoStore', {
    requires: [
               'MyApp.model.AppInfoModel'
           ],
	extend: 'Ext.data.Store',
    storeId: 'MYAppInfoStore',
    model: 'MyApp.model.AppInfoModel',
    
    autoLoad:true,

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            
            
//            proxy: me.processMyAjaxProxy({
//                type: 'ajax',
//                reader: {
//                    type: 'json'
//                }
//            })
        }, cfg)]);
    },
    proxy: {
        type: 'ajax',
        url : 'GetJobInfo/AppInfo',
        api: {
            read    : 'GetJobInfo/AppInfo',
            //update  : 'CreateJob/CreateApp',

        },
        reader: {
            type: 'json',
        },
        writer: {
            type: 'json',
            writeAllFields: true,
            encode:true,
            root: ''
        },
        listeners: {
            exception: function(proxy, response, operation){
                Ext.MessageBox.show({
                    title: 'REMOTE EXCEPTION',
                    msg: operation.getError(),
                    icon: Ext.MessageBox.ERROR,
                    buttons: Ext.Msg.OK
                });
            }
        }
    },
    data:[],
    processMyAjaxProxy: function(config) {
    	
        return config;
    }

});