/*
 * File: app/store/JobStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.JobStore', {
    extend: 'Ext.data.Store',
    storeId: 'MyStore',
    model: 'MyApp.model.JobsModel',
    requires: [
        'MyApp.model.JobsModel'
    ],
    autoLoad:true,
    proxy: {
    	
        type: 'ajax',
        url : 'GetJobInfo/index',
        api: {
            destroy : 'DeleteAbsJob/doDelete/delete.json'
        },
        reader: {
            type: 'json'
        },
        writer: {
            type: 'json',
            encode: true,
            root:'data'
        }
    },
    data: [
//           {
//               ID: '1',
//               JobID: '1',
//               JobName: 'update-train.train-model',
//               JobGuarantee: '1',
//               InputPath: '/user/root/bvc_env/update -train.train-model.tar',
//               RunCmd: 'sh -x ./bvc/bin/run_map.sh update-train train-model'
//           },
//           {
//               ID: '2',
//               JobID: '2',
//               JobName: 'update-train_train-model.map',
//               JobGuarantee: '0',
//               InputPath: '/user/root/bvc_env/update -train_train-model.map.tar',
//               RunCmd: 'sh -x ./bvc/bin/multi_map.sh update-train_train-model'
//           }
       ],
    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            
        }, cfg)]);
        
    }
	
});