/*
 * File: app/view/AdminPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AdminPanel', {
    extend: 'Ext.panel.Panel',
    alias : 'widget.AdminPanel',
    xtype: 'MyAdminPanel',
    height: 616,
    //width: 847,
    layout: {
        type: 'absolute'
    },
    title: '管理员窗口',
    MyRender:function(value){
    	if(value=="1"){
    		return "用户新创建";
    	}else if(value==2){
    		return "用户修改";
    	}else if(value==3){
    		return "通过审核";
    	}else if(value==4){
    		return "用户删除";
    	}else if(value==5){
    		return "已经上线";
    	}else if(value==6){
    		return "审核失败,作废";
    	}else if(value==7){
    		return "审核失败,重新修改";
    	}else if(value==8){
    		return "停止运行";
    	}        
    },
    initComponent: function() {
        var me = this;
        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    x: 180,
                    y: 55,
                    dock: 'top',
                    height: 40,
                    items: [
                        {
                            xtype: 'splitbutton',
                            text: '查看',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: '详细信息'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'splitbutton',
                            text: '管理员审核',
                            menu: {
                                xtype: 'menu',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: '通过'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: '重新修改'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: '作废'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: '批量通过'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'splitbutton',
                            text: '管理员上线',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: '单一上线'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: '批量上线'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'splitbutton',
                            text: '管理员回滚',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: '回滚选中至'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    x: 0,
                    y: 10,
                    height: 500,
                    activeTab: 0,
                    items: [
                        {
                        	xtype: 'panel',
                            height: 337,
                            title: '等待处理',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    id:'AdminAppop',
                                    height: 477,
                                    title: '待处理提交',
                                    store: 'AppopStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ID',
                                            text: 'ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'JobName',
                                            width:280,
                                            text: 'JobName'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'UserName',
                                            text: 'UserName'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'Status',
                                            text: '类型',
                                            renderer:this.MyRender
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'SubmitTime',
                                            text: '提交时间',
                                            width:150
                                        }
                                        
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                }
                            ]                            
                        },
                        {
                        	xtype: 'panel',
                            height: 337,
                            title: '已审核,待上线',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 477,
                                    id:'AdminAppopPassed',
                                    title: '待上线',
                                    store: 'AppopPassedStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ID',
                                            text: 'ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'JobName',
                                            width:280,
                                            text: 'JobName'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'UserName',
                                            text: 'UserName'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'Status',
                                            text: '类型',
                                            renderer:this.MyRender
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'SubmitTime',
                                            text: '提交时间',
                                            width:150
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ApprovalTime',
                                            text: '审核时间',
                                            width:150
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                }
                            ]
                        },
                        {
                        	xtype: 'panel',
                            height: 337,
                            title: '已经上线',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 477,
                                    id:'AdminAppopOnline',
                                    title: '已经上线',
                                    store: 'AppopOnlineStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ID',
                                            text: 'ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'JobName',
                                            width:280,
                                            text: 'JobName'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'UserName',
                                            text: 'UserName'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'Status',
                                            text: '类型',
                                            renderer:this.MyRender
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'SubmitTime',
                                            text: '提交时间',
                                            width:150
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'ApprovalTime',
                                            text: '审核时间',
                                            width:150
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'EffectTime',
                                            text: '上线时间',
                                            width:150
                                        }
                                        
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                }
                            ]
                        }
                    ]
                }
            ]
        });
        me.callParent(arguments);
    }

});