/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',
    alias : 'widget.MyWindow',
    autoShow: true,
    height: 500,
    width: 858,
    layout: {
        type: 'absolute'
    },
    title: 'CreateWindow',
    maximizable: true,
    items: [
            {
                xtype: 'gridpanel',
                id:'AllJobPanel',
                x: 10,
                y: 40,
                height: 400,
                width: 800,
                title: 'My Grid Panel',
                store: 'JobStore',
                columns: [
                    {
                        xtype: 'numbercolumn',
                        dataIndex: 'JobID',
                        text: 'JobID',
                        flex: 1,
                        format: '0000'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'JobName',
                        text: 'JobName',
                        flex: 4
                    },
                    {
                        xtype: 'gridcolumn',
                        width: 30,
                        dataIndex: 'JobGuarantee',
                        text: 'JobGuarantee',
                        flex: 1
                    },
                    {
                        xtype: 'gridcolumn',
                        width: 200,
                        dataIndex: 'InputPath',
                        text: 'InputPath',
                        flex: 5
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'RunCmd',
                        text: 'RunCmd',
                        flex: 5
                    }
                ],
                selModel: Ext.create('Ext.selection.CheckboxModel', {

                })
            },
            {
                xtype: 'splitbutton',
                x: 10,
                y: 10,
                text:'[创-建]',
                width: 120,
                showText: true,
                menu: {
                    xtype: 'menu',
                    width: 160,
                    items: [
                        {
                            xtype: 'menuitem',
                            text: '创建(模板)'
                     
                        },
                        {
                            xtype: 'menuitem',
                            text: '创建(默认值)'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        }
                    ]
                }
            },
            {
                xtype: 'button',
                id:'updatebutton',
                x: 300,
                y: 10,
                text: '更新'
            },            
            {
                xtype: 'textfield',
                x: 350,
                y: 10,
                fieldLabel: ''
            },
            {
                xtype: 'button',
                x: 490,
                y: 10,
                text: '搜索'
            },
            {
                xtype: 'splitbutton',
                text:'[修-改]',
                width: 120,
                x: 150,
                y: 10,
                showText: true,
                menu: {
                    xtype: 'menu',
                    width: 160,
                    items: [
                        {
                            xtype: 'menuitem',
                            text: '批量修改参数'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        }
                    ]
                }
            },
            {
                xtype: 'splitbutton',
                text:'[删-除]',
                width: 120,
                x: 580,
                y: 10,
                showText: true,
                menu: {
                    xtype: 'menu',
                    width: 160,
                    items: [
                        {
                            xtype: 'menuitem',
                            text: '删除'
                        },
                        {
                            xtype: 'menuitem',
                            text: '批量删除'
                        },
                        {
                            xtype: 'menuitem',
                            text: 'Menu Item'
                        }
                    ]
                }
            }
        ],
    initComponent: function() {
        var me = this;
        Ext.applyIf(me, {
            
        });       
        me.callParent(arguments);
    }

});