/*
 * File: app/model/AppopModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.AppopModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'JobName'
        },
        {
            name: 'UserName'
        },
        {
            name: 'OpIndex'
        },
        {
            name: 'Status'
        },
        {
            name: 'AppInfo'
        },
        {
            name: 'JobInfo'
        },
        {
            name: 'SubmitTime'
        },
        {
            name: 'ApprovalTime'
        },
        {
            name: 'EffectTime'
        }
    ]
});